### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by Reperiel** [tjjfvi/OctoPrint-SlicerSettingsTab#5]
Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).

**Comment by rob4226** [comment]
> Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).
> 
> Thanks for your work on this plugin.

@Reperiel I also really wanted to have all my plugins be Python 3 compatible, so I forked both this SlicerSettingsTab repository and also the SlicerSettingsParser plugin repository and upgraded them to work with Python 3. The URL's to use in order to install them with the OctoPrint plugin manager are:

**Python3- SlicerSettingsParser:**  https://github.com/Rob4226/OctoPrint-SlicerSettingsParser-Python3/archive/master.zip
**Python3- SlicerSettingsTab:** https://github.com/Rob4226/OctoPrint-SlicerSettingsTab-Python3/archive/master.zip

![image](https://user-images.githubusercontent.com/16749343/85334489-595d9780-b4a9-11ea-9c91-9018e8ea6a3c.png)

**Comment by ruedli** [comment]
Thanks for the Slicer settings parser, a feature I really depend on to know how I configured the colors for my MMU2 prints!
Same comment as for SlicerSettingsParser:  Is the upgrade downwards compatible, so may we expect the installed plugin to work with both Python 2 and Python 3? I would prefer to continue updating all plugins from the "Plugin Repository", or will the installation process bring in the correct version depending on the Python version installed?

**Comment by larsjuhw** [comment]
I adopted this plugin and added Python 3 support and some other changes in v1.1.0: https://github.com/larsjuhw/OctoPrint-SlicerSettingsTab/releases/tag/v1.1.0
